services:
  cafeteria:
    image: cafeteria-404:latest # Так же вместо latest можно использовать alpine, который подходит для случаев когда мало места или слабые характеристики
    container_name: cafeteria
    restart: always
    volumes:
      - ./cafe.db:/app/cafe.db
    ports:
      - 80:5000